DROP TABLE BASEBALL;
CREATE TABLE BASEBALL(
    PLAYERNUMBER NUMBER(2)CONSTRAINT PK_NUMBER PRIMARY KEY,
    PLAYERNAME NVARCHAR2(4),
    HOMERUN NUMBER(2),
    FOUL NUMBER(2),
    BINGLE NUMBER(2),
    BALL NUMBER(2),
    STRIKE NUMBER(2),
    FLYOUT NUMBER(2));

DROP SEQUENCE SEQ_BASEBALL;
CREATE SEQUENCE SEQ_BASEBALL
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
 

SELECT * FROM BASEBALL;